[font]
size = 12

[scrolling]
# Maximum number of lines in the scrollback buffer
history = 100000

[font.normal]
family = "Menlo"

[window.padding]
x = 7
y = 0

# Shell program and its arguments
# Default for Linux/BSD/macOS is $SHELL or user's login shell
# Default for Windows is "powershell"
[shell]
program = "/bin/bash"  # Example for Linux/BSD/macOS
args = ["-l"]
